#!/usr/bin/env bash

# atom, molecule, organism, page, template
TYPE=$1
NAME=$2
INLINE_CSS=false
INLINE_TEMPLATE=false

if [ "$TYPE" = "page" ]; then
    INLINE_CSS=true
elif [ "$TYPE" = "atom" ]; then
    INLINE_CSS=true
    INLINE_TEMPLATE=true
fi

(
  set -o xtrace &&
  ng g c --inline-style="$INLINE_CSS" --inline-template="$INLINE_TEMPLATE" --standalone=true components/"$TYPE"s/"$NAME"
) && echo "$TYPE $NAME created successfully." || echo "An error has occurred."
